import React from "react";
import { anticipate, motion , useScroll} from "motion/react";
import Bascis from "./Basics.jsx";
const App = () => {
const scrollY = useScroll().scrollYProgress
  console.log(useScroll())
  return (
    <div className="p-20 text-center text-neutral-50 font-mono">
    { console.log(useScroll())}

   {/* <Bascis/> */}

  <h1 className="text-4xl font-bold mb-8">
    Chapple Cheese😼😼  </h1>

<motion.div className="bg-red-300 w-full h-3  fixed top-0 origin-left left-0 "
style={{
  scaleX: scrollY
}}
>

</motion.div>

  <p className="" >
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quas delectus quia molestias earum ducimus explicabo incidunt corrupti facere excepturi animi, veniam facilis, dolores ipsa sit itaque, magni minima ea at laboriosam. Quasi magni atque facere reiciendis cumque quaerat nemo unde dicta sapiente excepturi suscipit aliquid ipsum, facilis amet provident omnis illum vero, illo voluptatum accusamus impedit. Similique libero optio ad saepe, impedit possimus vero molestias. Molestias obcaecati asperiores impedit quisquam, labore autem nostrum aspernatur quos dolore, officia reprehenderit architecto, repellendus nobis quae. Adipisci, et dolorem praesentium repellendus eius deserunt repudiandae excepturi ea ipsum fugiat ducimus nihil distinctio sequi hic.
    <br /> <br /> <br /> <br />
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam numquam ipsa quia sapiente quo natus eligendi totam. Laboriosam sunt dignissimos numquam consequuntur provident, aspernatur aliquid non ex modi hic, harum enim? Blanditiis laboriosam beatae culpa cumque reprehenderit. Exercitationem fugit perferendis minima voluptate velit quisquam placeat delectus quas, a vel iusto consequatur eaque assumenda ab maxime quis, nemo cupiditate molestiae praesentium, facere dignissimos quia. Recusandae dolorum quisquam ea, sint, amet cumque laborum mollitia, laudantium optio modi sunt veniam. Quisquam ipsum deserunt molestias possimus magnam, eligendi, id placeat quaerat harum porro facere perferendis voluptate, modi dolore quia error. Eveniet earum dolorem doloremque inventore perspiciatis ipsam sequi tempore veritatis odit debitis architecto autem unde fugit nihil eaque eos velit possimus placeat voluptate beatae, facilis dolores, explicabo, excepturi corporis. Totam mollitia neque excepturi minima modi earum labore numquam quis? Cumque aliquam blanditiis architecto consequuntur distinctio soluta, mollitia ullam commodi magnam, sed iure odit molestiae modi perferendis. Perspiciatis tempora illum, culpa reprehenderit aperiam sed voluptate impedit adipisci commodi! Impedit non cumque numquam iste vitae maiores ipsa suscipit pariatur. Iusto, praesentium! Tempora amet ex voluptatum architecto esse possimus accusamus sequi minima quia, quis ipsam harum alias consequatur voluptas similique nisi repellat omnis quisquam error dolores eos? 
    <br /> <br /> <br /> <br />

    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt error doloribus saepe molestiae est temporibus non asperiores pariatur totam quaerat? Ratione blanditiis repudiandae porro quis atque accusantium delectus quaerat. Dolores blanditiis nam cupiditate repudiandae. Labore ipsum voluptates nemo exercitationem dicta, iusto laborum ex dignissimos rerum? Voluptatibus quam deserunt dolorum sed doloribus cupiditate ipsum maxime veritatis ab, quibusdam pariatur laborum quia, necessitatibus qui eius dolore harum rerum doloremque blanditiis sint accusantium, ullam amet! Explicabo qui aliquam iure deserunt fugit, minus et modi praesentium, sed illo ipsum beatae ipsa. At, illum fuga impedit numquam iusto qui amet pariatur eius? Iusto culpa soluta labore, nihil dolor quia. Iste maxime enim alias atque, modi quo doloribus. Blanditiis placeat accusamus nesciunt dolore iste, sit dignissimos molestiae ipsa quis, perferendis ea alias nemo incidunt reiciendis mollitia vel saepe ducimus adipisci voluptatibus? Quod sed tempora nobis! Minima possimus, soluta autem quod ullam dolorum assumenda perspiciatis temporibus magni veniam alias blanditiis sit natus ad doloremque ea, beatae molestiae cum repellat atque. Cumque, laudantium enim possimus placeat vitae et fuga ipsum aliquam! Hic, maxime. Ipsum, sunt cum. Nobis doloribus, expedita, alias veniam corporis et ex cum doloremque iste temporibus harum quos id iusto vitae iure ullam sapiente odit suscipit.
  </p>
  <p className="" >
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quas delectus quia molestias earum ducimus explicabo incidunt corrupti facere excepturi animi, veniam facilis, dolores ipsa sit itaque, magni minima ea at laboriosam. Quasi magni atque facere reiciendis cumque quaerat nemo unde dicta sapiente excepturi suscipit aliquid ipsum, facilis amet provident omnis illum vero, illo voluptatum accusamus impedit. Similique libero optio ad saepe, impedit possimus vero molestias. Molestias obcaecati asperiores impedit quisquam, labore autem nostrum aspernatur quos dolore, officia reprehenderit architecto, repellendus nobis quae. Adipisci, et dolorem praesentium repellendus eius deserunt repudiandae excepturi ea ipsum fugiat ducimus nihil distinctio sequi hic.
    <br /> <br /> <br /> <br />
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam numquam ipsa quia sapiente quo natus eligendi totam. Laboriosam sunt dignissimos numquam consequuntur provident, aspernatur aliquid non ex modi hic, harum enim? Blanditiis laboriosam beatae culpa cumque reprehenderit. Exercitationem fugit perferendis minima voluptate velit quisquam placeat delectus quas, a vel iusto consequatur eaque assumenda ab maxime quis, nemo cupiditate molestiae praesentium, facere dignissimos quia. Recusandae dolorum quisquam ea, sint, amet cumque laborum mollitia, laudantium optio modi sunt veniam. Quisquam ipsum deserunt molestias possimus magnam, eligendi, id placeat quaerat harum porro facere perferendis voluptate, modi dolore quia error. Eveniet earum dolorem doloremque inventore perspiciatis ipsam sequi tempore veritatis odit debitis architecto autem unde fugit nihil eaque eos velit possimus placeat voluptate beatae, facilis dolores, explicabo, excepturi corporis. Totam mollitia neque excepturi minima modi earum labore numquam quis? Cumque aliquam blanditiis architecto consequuntur distinctio soluta, mollitia ullam commodi magnam, sed iure odit molestiae modi perferendis. Perspiciatis tempora illum, culpa reprehenderit aperiam sed voluptate impedit adipisci commodi! Impedit non cumque numquam iste vitae maiores ipsa suscipit pariatur. Iusto, praesentium! Tempora amet ex voluptatum architecto esse possimus accusamus sequi minima quia, quis ipsam harum alias consequatur voluptas similique nisi repellat omnis quisquam error dolores eos? 
    <br /> <br /> <br /> <br />

    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt error doloribus saepe molestiae est temporibus non asperiores pariatur totam quaerat? Ratione blanditiis repudiandae porro quis atque accusantium delectus quaerat. Dolores blanditiis nam cupiditate repudiandae. Labore ipsum voluptates nemo exercitationem dicta, iusto laborum ex dignissimos rerum? Voluptatibus quam deserunt dolorum sed doloribus cupiditate ipsum maxime veritatis ab, quibusdam pariatur laborum quia, necessitatibus qui eius dolore harum rerum doloremque blanditiis sint accusantium, ullam amet! Explicabo qui aliquam iure deserunt fugit, minus et modi praesentium, sed illo ipsum beatae ipsa. At, illum fuga impedit numquam iusto qui amet pariatur eius? Iusto culpa soluta labore, nihil dolor quia. Iste maxime enim alias atque, modi quo doloribus. Blanditiis placeat accusamus nesciunt dolore iste, sit dignissimos molestiae ipsa quis, perferendis ea alias nemo incidunt reiciendis mollitia vel saepe ducimus adipisci voluptatibus? Quod sed tempora nobis! Minima possimus, soluta autem quod ullam dolorum assumenda perspiciatis temporibus magni veniam alias blanditiis sit natus ad doloremque ea, beatae molestiae cum repellat atque. Cumque, laudantium enim possimus placeat vitae et fuga ipsum aliquam! Hic, maxime. Ipsum, sunt cum. Nobis doloribus, expedita, alias veniam corporis et ex cum doloremque iste temporibus harum quos id iusto vitae iure ullam sapiente odit suscipit.
  </p>
  <p className="" >
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quas delectus quia molestias earum ducimus explicabo incidunt corrupti facere excepturi animi, veniam facilis, dolores ipsa sit itaque, magni minima ea at laboriosam. Quasi magni atque facere reiciendis cumque quaerat nemo unde dicta sapiente excepturi suscipit aliquid ipsum, facilis amet provident omnis illum vero, illo voluptatum accusamus impedit. Similique libero optio ad saepe, impedit possimus vero molestias. Molestias obcaecati asperiores impedit quisquam, labore autem nostrum aspernatur quos dolore, officia reprehenderit architecto, repellendus nobis quae. Adipisci, et dolorem praesentium repellendus eius deserunt repudiandae excepturi ea ipsum fugiat ducimus nihil distinctio sequi hic.
    <br /> <br /> <br /> <br />
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam numquam ipsa quia sapiente quo natus eligendi totam. Laboriosam sunt dignissimos numquam consequuntur provident, aspernatur aliquid non ex modi hic, harum enim? Blanditiis laboriosam beatae culpa cumque reprehenderit. Exercitationem fugit perferendis minima voluptate velit quisquam placeat delectus quas, a vel iusto consequatur eaque assumenda ab maxime quis, nemo cupiditate molestiae praesentium, facere dignissimos quia. Recusandae dolorum quisquam ea, sint, amet cumque laborum mollitia, laudantium optio modi sunt veniam. Quisquam ipsum deserunt molestias possimus magnam, eligendi, id placeat quaerat harum porro facere perferendis voluptate, modi dolore quia error. Eveniet earum dolorem doloremque inventore perspiciatis ipsam sequi tempore veritatis odit debitis architecto autem unde fugit nihil eaque eos velit possimus placeat voluptate beatae, facilis dolores, explicabo, excepturi corporis. Totam mollitia neque excepturi minima modi earum labore numquam quis? Cumque aliquam blanditiis architecto consequuntur distinctio soluta, mollitia ullam commodi magnam, sed iure odit molestiae modi perferendis. Perspiciatis tempora illum, culpa reprehenderit aperiam sed voluptate impedit adipisci commodi! Impedit non cumque numquam iste vitae maiores ipsa suscipit pariatur. Iusto, praesentium! Tempora amet ex voluptatum architecto esse possimus accusamus sequi minima quia, quis ipsam harum alias consequatur voluptas similique nisi repellat omnis quisquam error dolores eos? 
    <br /> <br /> <br /> <br />

    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt error doloribus saepe molestiae est temporibus non asperiores pariatur totam quaerat? Ratione blanditiis repudiandae porro quis atque accusantium delectus quaerat. Dolores blanditiis nam cupiditate repudiandae. Labore ipsum voluptates nemo exercitationem dicta, iusto laborum ex dignissimos rerum? Voluptatibus quam deserunt dolorum sed doloribus cupiditate ipsum maxime veritatis ab, quibusdam pariatur laborum quia, necessitatibus qui eius dolore harum rerum doloremque blanditiis sint accusantium, ullam amet! Explicabo qui aliquam iure deserunt fugit, minus et modi praesentium, sed illo ipsum beatae ipsa. At, illum fuga impedit numquam iusto qui amet pariatur eius? Iusto culpa soluta labore, nihil dolor quia. Iste maxime enim alias atque, modi quo doloribus. Blanditiis placeat accusamus nesciunt dolore iste, sit dignissimos molestiae ipsa quis, perferendis ea alias nemo incidunt reiciendis mollitia vel saepe ducimus adipisci voluptatibus? Quod sed tempora nobis! Minima possimus, soluta autem quod ullam dolorum assumenda perspiciatis temporibus magni veniam alias blanditiis sit natus ad doloremque ea, beatae molestiae cum repellat atque. Cumque, laudantium enim possimus placeat vitae et fuga ipsum aliquam! Hic, maxime. Ipsum, sunt cum. Nobis doloribus, expedita, alias veniam corporis et ex cum doloremque iste temporibus harum quos id iusto vitae iure ullam sapiente odit suscipit.
  </p>
  <p className="" >
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo quas delectus quia molestias earum ducimus explicabo incidunt corrupti facere excepturi animi, veniam facilis, dolores ipsa sit itaque, magni minima ea at laboriosam. Quasi magni atque facere reiciendis cumque quaerat nemo unde dicta sapiente excepturi suscipit aliquid ipsum, facilis amet provident omnis illum vero, illo voluptatum accusamus impedit. Similique libero optio ad saepe, impedit possimus vero molestias. Molestias obcaecati asperiores impedit quisquam, labore autem nostrum aspernatur quos dolore, officia reprehenderit architecto, repellendus nobis quae. Adipisci, et dolorem praesentium repellendus eius deserunt repudiandae excepturi ea ipsum fugiat ducimus nihil distinctio sequi hic.
    <br /> <br /> <br /> <br />
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam numquam ipsa quia sapiente quo natus eligendi totam. Laboriosam sunt dignissimos numquam consequuntur provident, aspernatur aliquid non ex modi hic, harum enim? Blanditiis laboriosam beatae culpa cumque reprehenderit. Exercitationem fugit perferendis minima voluptate velit quisquam placeat delectus quas, a vel iusto consequatur eaque assumenda ab maxime quis, nemo cupiditate molestiae praesentium, facere dignissimos quia. Recusandae dolorum quisquam ea, sint, amet cumque laborum mollitia, laudantium optio modi sunt veniam. Quisquam ipsum deserunt molestias possimus magnam, eligendi, id placeat quaerat harum porro facere perferendis voluptate, modi dolore quia error. Eveniet earum dolorem doloremque inventore perspiciatis ipsam sequi tempore veritatis odit debitis architecto autem unde fugit nihil eaque eos velit possimus placeat voluptate beatae, facilis dolores, explicabo, excepturi corporis. Totam mollitia neque excepturi minima modi earum labore numquam quis? Cumque aliquam blanditiis architecto consequuntur distinctio soluta, mollitia ullam commodi magnam, sed iure odit molestiae modi perferendis. Perspiciatis tempora illum, culpa reprehenderit aperiam sed voluptate impedit adipisci commodi! Impedit non cumque numquam iste vitae maiores ipsa suscipit pariatur. Iusto, praesentium! Tempora amet ex voluptatum architecto esse possimus accusamus sequi minima quia, quis ipsam harum alias consequatur voluptas similique nisi repellat omnis quisquam error dolores eos? 
    <br /> <br /> <br /> <br />

    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt error doloribus saepe molestiae est temporibus non asperiores pariatur totam quaerat? Ratione blanditiis repudiandae porro quis atque accusantium delectus quaerat. Dolores blanditiis nam cupiditate repudiandae. Labore ipsum voluptates nemo exercitationem dicta, iusto laborum ex dignissimos rerum? Voluptatibus quam deserunt dolorum sed doloribus cupiditate ipsum maxime veritatis ab, quibusdam pariatur laborum quia, necessitatibus qui eius dolore harum rerum doloremque blanditiis sint accusantium, ullam amet! Explicabo qui aliquam iure deserunt fugit, minus et modi praesentium, sed illo ipsum beatae ipsa. At, illum fuga impedit numquam iusto qui amet pariatur eius? Iusto culpa soluta labore, nihil dolor quia. Iste maxime enim alias atque, modi quo doloribus. Blanditiis placeat accusamus nesciunt dolore iste, sit dignissimos molestiae ipsa quis, perferendis ea alias nemo incidunt reiciendis mollitia vel saepe ducimus adipisci voluptatibus? Quod sed tempora nobis! Minima possimus, soluta autem quod ullam dolorum assumenda perspiciatis temporibus magni veniam alias blanditiis sit natus ad doloremque ea, beatae molestiae cum repellat atque. Cumque, laudantium enim possimus placeat vitae et fuga ipsum aliquam! Hic, maxime. Ipsum, sunt cum. Nobis doloribus, expedita, alias veniam corporis et ex cum doloremque iste temporibus harum quos id iusto vitae iure ullam sapiente odit suscipit.
  </p>
   </div>
   
);
};

export default App;
